#!/bin/bash

EXEC="python bin/app.py 9090 >>/dev/null"
FOLDERS="bin templates static numberGame"
WATCH_SECONDS=1

start() {
  echo starting $EXEC
  $EXEC & export PID=$!
  echo process pid is $PID
}

restart() {
  echo files changed, killing the process
  kill -9 $PID
  wait $PID 2>/dev/null
  start
}

quit() {
  echo "cleaning up before exit, bye minik!"
  kill -9 $PID
  exit
}

watch() {
  start
  echo watching folders $1/ every 1 seconds.
  while [[ true ]]
    do
        files=`find $1 -type f -mtime -1s`
        if [[ $files == "" ]] ; then
            echo "nothing changed" >>/dev/null
        else
            echo changed, $files
            restart
        fi
        sleep $WATCH_SECONDS
    done
}

trap ctrl_c INT

function ctrl_c() {
  quit
}

watch "$FOLDERS"
